name = "FactorPostProcessing"
uuid = "44248d4f-322e-4d82-bed2-546ef3e908c1"
authors = ["Gabe Hassler <gabriel.w.hassler@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BeastUtils = "af749cb1-4ea1-40dc-96cd-a9902a2c5721"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
