name = "FactorPostProcessing"
uuid = "44248d4f-322e-4d82-bed2-546ef3e908c1"
authors = ["Gabe Hassler <gabriel.w.hassler@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
